import type Sub from '../Sub';

const toSubTime = (str: string): string => {
  let n: string[] = [];
  let sx = '';
  let x = str.split(/[:.]/).map((item) => Number(item));
  x = str.split(/[:.]/).map((item) => Number(item));
  x[3] = Number(`0.${('00' + x[3]).slice(-3)}`);
  const seconds = x[0] * 60 * 60 + x[1] * 60 + x[2] + Number(x[3]);
  sx = seconds.toFixed(2);
  const parts = sx.toString().split('.');
  n.unshift(parts[1]);
  let total = Number(parts[0]);
  n.unshift(('0' + (total % 60).toString()).slice(-2));
  total = Math.floor(total / 60);
  n.unshift(('0' + (total % 60).toString()).slice(-2));
  total = Math.floor(total / 60);
  n.unshift((total % 60).toString());
  return `${n.slice(0, 3).join(':')}.${n[3]}`;
};

export default function sub2ass(sub: Sub[]): string {
  return `
[Script Info]
; // Generated by Subtitle Editor
Synch Point:1
ScriptType:v4.00+
Collisions:Normal

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default, Microsoft YaHei, 20, &H00FFFFFF, &H000000FF, &H00000000, &H00000000, 0, 0, 0, 0, 100, 100, 0, 0, 1, 1, 0, 2, 10, 10, 10, 134

[Events]
Format: Layer, Start, End, Style, Actor, MarginL, MarginR, MarginV, Effect, Text
${sub
    .map((item) => {
      const start = toSubTime(item.start);
      const end = toSubTime(item.end);
      const text = item.text.replace(/\r?\n/g, '\\N');
      return `Dialogue: 0,${start},${end},Default,NTP,0000,0000,0000,,${text}`;
    })
    .join('\n')}
  `.trim();
}
